begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions, pg_catalog;
select plan(96);
select ok((select relrowsecurity from pg_catalog.pg_class where oid='public.inventory_import_jobs'::regclass), 'inventory_import_jobs enables RLS');
select ok(not has_table_privilege('anon', 'public.inventory_import_jobs', 'SELECT'), 'anon cannot use inventory_import_jobs SELECT');
select ok(not has_table_privilege('anon', 'public.inventory_import_jobs', 'INSERT'), 'anon cannot use inventory_import_jobs INSERT');
select ok(not has_table_privilege('anon', 'public.inventory_import_jobs', 'UPDATE'), 'anon cannot use inventory_import_jobs UPDATE');
select ok(not has_table_privilege('anon', 'public.inventory_import_jobs', 'DELETE'), 'anon cannot use inventory_import_jobs DELETE');
select ok(not has_table_privilege('anon', 'public.inventory_import_jobs', 'TRUNCATE'), 'anon cannot use inventory_import_jobs TRUNCATE');
select ok(has_table_privilege('authenticated', 'public.inventory_import_jobs', 'SELECT'), 'authenticated has inventory_import_jobs SELECT');
select ok(has_table_privilege('authenticated', 'public.inventory_import_jobs', 'INSERT'), 'authenticated has inventory_import_jobs INSERT');
select ok(not has_table_privilege('authenticated', 'public.inventory_import_jobs', 'UPDATE'), 'authenticated cannot use inventory_import_jobs UPDATE');
select ok(not has_table_privilege('authenticated', 'public.inventory_import_jobs', 'DELETE'), 'authenticated cannot use inventory_import_jobs DELETE');
select ok(not has_table_privilege('authenticated', 'public.inventory_import_jobs', 'TRUNCATE'), 'authenticated cannot use inventory_import_jobs TRUNCATE');
select ok(has_table_privilege('service_role', 'public.inventory_import_jobs', 'SELECT'), 'service_role has inventory_import_jobs SELECT');
select ok(has_table_privilege('service_role', 'public.inventory_import_jobs', 'INSERT'), 'service_role has inventory_import_jobs INSERT');
select ok(has_table_privilege('service_role', 'public.inventory_import_jobs', 'UPDATE'), 'service_role has inventory_import_jobs UPDATE');
select ok(has_table_privilege('service_role', 'public.inventory_import_jobs', 'DELETE'), 'service_role has inventory_import_jobs DELETE');
select ok(has_table_privilege('service_role', 'public.inventory_import_jobs', 'TRUNCATE'), 'service_role has inventory_import_jobs TRUNCATE');
select ok((select relrowsecurity from pg_catalog.pg_class where oid='public.inventory_import_rows'::regclass), 'inventory_import_rows enables RLS');
select ok(not has_table_privilege('anon', 'public.inventory_import_rows', 'SELECT'), 'anon cannot use inventory_import_rows SELECT');
select ok(not has_table_privilege('anon', 'public.inventory_import_rows', 'INSERT'), 'anon cannot use inventory_import_rows INSERT');
select ok(not has_table_privilege('anon', 'public.inventory_import_rows', 'UPDATE'), 'anon cannot use inventory_import_rows UPDATE');
select ok(not has_table_privilege('anon', 'public.inventory_import_rows', 'DELETE'), 'anon cannot use inventory_import_rows DELETE');
select ok(not has_table_privilege('anon', 'public.inventory_import_rows', 'TRUNCATE'), 'anon cannot use inventory_import_rows TRUNCATE');
select ok(has_table_privilege('authenticated', 'public.inventory_import_rows', 'SELECT'), 'authenticated has inventory_import_rows SELECT');
select ok(not has_table_privilege('authenticated', 'public.inventory_import_rows', 'INSERT'), 'authenticated cannot use inventory_import_rows INSERT');
select ok(not has_table_privilege('authenticated', 'public.inventory_import_rows', 'UPDATE'), 'authenticated cannot use inventory_import_rows UPDATE');
select ok(not has_table_privilege('authenticated', 'public.inventory_import_rows', 'DELETE'), 'authenticated cannot use inventory_import_rows DELETE');
select ok(not has_table_privilege('authenticated', 'public.inventory_import_rows', 'TRUNCATE'), 'authenticated cannot use inventory_import_rows TRUNCATE');
select ok(has_table_privilege('service_role', 'public.inventory_import_rows', 'SELECT'), 'service_role has inventory_import_rows SELECT');
select ok(has_table_privilege('service_role', 'public.inventory_import_rows', 'INSERT'), 'service_role has inventory_import_rows INSERT');
select ok(has_table_privilege('service_role', 'public.inventory_import_rows', 'UPDATE'), 'service_role has inventory_import_rows UPDATE');
select ok(has_table_privilege('service_role', 'public.inventory_import_rows', 'DELETE'), 'service_role has inventory_import_rows DELETE');
select ok(has_table_privilege('service_role', 'public.inventory_import_rows', 'TRUNCATE'), 'service_role has inventory_import_rows TRUNCATE');
select ok((select relrowsecurity from pg_catalog.pg_class where oid='public.inventory_import_profiles'::regclass), 'inventory_import_profiles enables RLS');
select ok(not has_table_privilege('anon', 'public.inventory_import_profiles', 'SELECT'), 'anon cannot use inventory_import_profiles SELECT');
select ok(not has_table_privilege('anon', 'public.inventory_import_profiles', 'INSERT'), 'anon cannot use inventory_import_profiles INSERT');
select ok(not has_table_privilege('anon', 'public.inventory_import_profiles', 'UPDATE'), 'anon cannot use inventory_import_profiles UPDATE');
select ok(not has_table_privilege('anon', 'public.inventory_import_profiles', 'DELETE'), 'anon cannot use inventory_import_profiles DELETE');
select ok(not has_table_privilege('anon', 'public.inventory_import_profiles', 'TRUNCATE'), 'anon cannot use inventory_import_profiles TRUNCATE');
select ok(has_table_privilege('authenticated', 'public.inventory_import_profiles', 'SELECT'), 'authenticated has inventory_import_profiles SELECT');
select ok(has_table_privilege('authenticated', 'public.inventory_import_profiles', 'INSERT'), 'authenticated has inventory_import_profiles INSERT');
select ok(has_table_privilege('authenticated', 'public.inventory_import_profiles', 'UPDATE'), 'authenticated has inventory_import_profiles UPDATE');
select ok(has_table_privilege('authenticated', 'public.inventory_import_profiles', 'DELETE'), 'authenticated has inventory_import_profiles DELETE');
select ok(not has_table_privilege('authenticated', 'public.inventory_import_profiles', 'TRUNCATE'), 'authenticated cannot use inventory_import_profiles TRUNCATE');
select ok(has_table_privilege('service_role', 'public.inventory_import_profiles', 'SELECT'), 'service_role has inventory_import_profiles SELECT');
select ok(has_table_privilege('service_role', 'public.inventory_import_profiles', 'INSERT'), 'service_role has inventory_import_profiles INSERT');
select ok(has_table_privilege('service_role', 'public.inventory_import_profiles', 'UPDATE'), 'service_role has inventory_import_profiles UPDATE');
select ok(has_table_privilege('service_role', 'public.inventory_import_profiles', 'DELETE'), 'service_role has inventory_import_profiles DELETE');
select ok(has_table_privilege('service_role', 'public.inventory_import_profiles', 'TRUNCATE'), 'service_role has inventory_import_profiles TRUNCATE');
select ok((select relrowsecurity from pg_catalog.pg_class where oid='public.cabinet_trash'::regclass), 'cabinet_trash enables RLS');
select ok(not has_table_privilege('anon', 'public.cabinet_trash', 'SELECT'), 'anon cannot use cabinet_trash SELECT');
select ok(not has_table_privilege('anon', 'public.cabinet_trash', 'INSERT'), 'anon cannot use cabinet_trash INSERT');
select ok(not has_table_privilege('anon', 'public.cabinet_trash', 'UPDATE'), 'anon cannot use cabinet_trash UPDATE');
select ok(not has_table_privilege('anon', 'public.cabinet_trash', 'DELETE'), 'anon cannot use cabinet_trash DELETE');
select ok(not has_table_privilege('anon', 'public.cabinet_trash', 'TRUNCATE'), 'anon cannot use cabinet_trash TRUNCATE');
select ok(has_table_privilege('authenticated', 'public.cabinet_trash', 'SELECT'), 'authenticated has cabinet_trash SELECT');
select ok(not has_table_privilege('authenticated', 'public.cabinet_trash', 'INSERT'), 'authenticated cannot use cabinet_trash INSERT');
select ok(not has_table_privilege('authenticated', 'public.cabinet_trash', 'UPDATE'), 'authenticated cannot use cabinet_trash UPDATE');
select ok(not has_table_privilege('authenticated', 'public.cabinet_trash', 'DELETE'), 'authenticated cannot use cabinet_trash DELETE');
select ok(not has_table_privilege('authenticated', 'public.cabinet_trash', 'TRUNCATE'), 'authenticated cannot use cabinet_trash TRUNCATE');
select ok(has_table_privilege('service_role', 'public.cabinet_trash', 'SELECT'), 'service_role has cabinet_trash SELECT');
select ok(has_table_privilege('service_role', 'public.cabinet_trash', 'INSERT'), 'service_role has cabinet_trash INSERT');
select ok(has_table_privilege('service_role', 'public.cabinet_trash', 'UPDATE'), 'service_role has cabinet_trash UPDATE');
select ok(has_table_privilege('service_role', 'public.cabinet_trash', 'DELETE'), 'service_role has cabinet_trash DELETE');
select ok(has_table_privilege('service_role', 'public.cabinet_trash', 'TRUNCATE'), 'service_role has cabinet_trash TRUNCATE');
select ok(not has_function_privilege('anon', 'public.get_cabinet_state_v2(uuid)', 'EXECUTE'), 'get_cabinet_state_v2(uuid) is bounded for anon');
select ok(has_function_privilege('authenticated', 'public.get_cabinet_state_v2(uuid)', 'EXECUTE'), 'get_cabinet_state_v2(uuid) is bounded for authenticated');
select ok(not has_function_privilege('service_role', 'public.get_cabinet_state_v2(uuid)', 'EXECUTE'), 'get_cabinet_state_v2(uuid) is bounded for service_role');
select ok(not has_function_privilege('anon', 'public.get_cabinet_trash_v2(uuid)', 'EXECUTE'), 'get_cabinet_trash_v2(uuid) is bounded for anon');
select ok(has_function_privilege('authenticated', 'public.get_cabinet_trash_v2(uuid)', 'EXECUTE'), 'get_cabinet_trash_v2(uuid) is bounded for authenticated');
select ok(not has_function_privilege('service_role', 'public.get_cabinet_trash_v2(uuid)', 'EXECUTE'), 'get_cabinet_trash_v2(uuid) is bounded for service_role');
select ok(not has_function_privilege('anon', 'public.create_cabinet_v2(text,text,integer,integer,integer,uuid)', 'EXECUTE'), 'create_cabinet_v2(text,text,integer,integer,integer,uuid) is bounded for anon');
select ok(has_function_privilege('authenticated', 'public.create_cabinet_v2(text,text,integer,integer,integer,uuid)', 'EXECUTE'), 'create_cabinet_v2(text,text,integer,integer,integer,uuid) is bounded for authenticated');
select ok(not has_function_privilege('service_role', 'public.create_cabinet_v2(text,text,integer,integer,integer,uuid)', 'EXECUTE'), 'create_cabinet_v2(text,text,integer,integer,integer,uuid) is bounded for service_role');
select ok(not has_function_privilege('anon', 'public.save_cabinet_state_v2(uuid,jsonb,integer,integer,integer,bigint,uuid[],uuid[])', 'EXECUTE'), 'save_cabinet_state_v2(uuid,jsonb,integer,integer,integer,bigint,uuid[],uuid[]) is bounded for anon');
select ok(has_function_privilege('authenticated', 'public.save_cabinet_state_v2(uuid,jsonb,integer,integer,integer,bigint,uuid[],uuid[])', 'EXECUTE'), 'save_cabinet_state_v2(uuid,jsonb,integer,integer,integer,bigint,uuid[],uuid[]) is bounded for authenticated');
select ok(not has_function_privilege('service_role', 'public.save_cabinet_state_v2(uuid,jsonb,integer,integer,integer,bigint,uuid[],uuid[])', 'EXECUTE'), 'save_cabinet_state_v2(uuid,jsonb,integer,integer,integer,bigint,uuid[],uuid[]) is bounded for service_role');
select ok(not has_function_privilege('anon', 'public.restore_cabinet_trash_v2(uuid,uuid,bigint)', 'EXECUTE'), 'restore_cabinet_trash_v2(uuid,uuid,bigint) is bounded for anon');
select ok(has_function_privilege('authenticated', 'public.restore_cabinet_trash_v2(uuid,uuid,bigint)', 'EXECUTE'), 'restore_cabinet_trash_v2(uuid,uuid,bigint) is bounded for authenticated');
select ok(not has_function_privilege('service_role', 'public.restore_cabinet_trash_v2(uuid,uuid,bigint)', 'EXECUTE'), 'restore_cabinet_trash_v2(uuid,uuid,bigint) is bounded for service_role');
select ok(not has_function_privilege('anon', 'public.update_cabinet_item_ghs_v2(uuid,uuid,text,text,jsonb,text,timestamptz)', 'EXECUTE'), 'update_cabinet_item_ghs_v2(uuid,uuid,text,text,jsonb,text,timestamptz) is bounded for anon');
select ok(has_function_privilege('authenticated', 'public.update_cabinet_item_ghs_v2(uuid,uuid,text,text,jsonb,text,timestamptz)', 'EXECUTE'), 'update_cabinet_item_ghs_v2(uuid,uuid,text,text,jsonb,text,timestamptz) is bounded for authenticated');
select ok(not has_function_privilege('service_role', 'public.update_cabinet_item_ghs_v2(uuid,uuid,text,text,jsonb,text,timestamptz)', 'EXECUTE'), 'update_cabinet_item_ghs_v2(uuid,uuid,text,text,jsonb,text,timestamptz) is bounded for service_role');
select ok(not has_function_privilege('anon', 'public.purge_expired_cabinet_trash_v2()', 'EXECUTE'), 'purge_expired_cabinet_trash_v2() is bounded for anon');
select ok(not has_function_privilege('authenticated', 'public.purge_expired_cabinet_trash_v2()', 'EXECUTE'), 'purge_expired_cabinet_trash_v2() is bounded for authenticated');
select ok(has_function_privilege('service_role', 'public.purge_expired_cabinet_trash_v2()', 'EXECUTE'), 'purge_expired_cabinet_trash_v2() is bounded for service_role');
select ok(not has_function_privilege('anon', 'public.save_inventory_import_v1(uuid,integer,jsonb,jsonb,uuid)', 'EXECUTE'), 'save_inventory_import_v1(uuid,integer,jsonb,jsonb,uuid) is bounded for anon');
select ok(has_function_privilege('authenticated', 'public.save_inventory_import_v1(uuid,integer,jsonb,jsonb,uuid)', 'EXECUTE'), 'save_inventory_import_v1(uuid,integer,jsonb,jsonb,uuid) is bounded for authenticated');
select ok(not has_function_privilege('service_role', 'public.save_inventory_import_v1(uuid,integer,jsonb,jsonb,uuid)', 'EXECUTE'), 'save_inventory_import_v1(uuid,integer,jsonb,jsonb,uuid) is bounded for service_role');
select ok(not has_function_privilege('anon', 'public.commit_inventory_import_batch_v1(uuid,integer,jsonb)', 'EXECUTE'), 'commit_inventory_import_batch_v1(uuid,integer,jsonb) is bounded for anon');
select ok(has_function_privilege('authenticated', 'public.commit_inventory_import_batch_v1(uuid,integer,jsonb)', 'EXECUTE'), 'commit_inventory_import_batch_v1(uuid,integer,jsonb) is bounded for authenticated');
select ok(not has_function_privilege('service_role', 'public.commit_inventory_import_batch_v1(uuid,integer,jsonb)', 'EXECUTE'), 'commit_inventory_import_batch_v1(uuid,integer,jsonb) is bounded for service_role');
select ok(not has_function_privilege('authenticated','public.save_cabinet_state_atomic(uuid,jsonb,integer,integer,integer)','EXECUTE'), 'save_cabinet_state_atomic(uuid,jsonb,integer,integer,integer) is retired for browser clients');
select ok(not has_function_privilege('authenticated','public.save_cabinet_state_with_ghs(uuid,jsonb,integer,integer,integer)','EXECUTE'), 'save_cabinet_state_with_ghs(uuid,jsonb,integer,integer,integer) is retired for browser clients');
select ok(not has_function_privilege('authenticated','public.save_cabinet_state_with_dates(uuid,jsonb,integer,integer,integer)','EXECUTE'), 'save_cabinet_state_with_dates(uuid,jsonb,integer,integer,integer) is retired for browser clients');
select ok(not has_table_privilege('authenticated','public.cabinet_shelves','DELETE'), 'cabinet_shelves direct browser deletion is blocked');
select ok(not has_table_privilege('authenticated','public.cabinet_items','DELETE'), 'cabinet_items direct browser deletion is blocked');
select * from finish();
rollback;
