/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/storage-backup/wrangler.staging.jsonc --include-runtime=false --strict-vars=false workers/storage-backup/worker-configuration.d.ts` (hash: 8855eb55aa7289df3ac87e49f3220df9)
interface __BaseEnv_Env {
	BURILLAB_RUNTIME_CONFIG: KVNamespace;
	CABINET_BACKUPS: R2Bucket;
	BACKUP_ENVIRONMENT: string;
	SUPABASE_PROJECT_REF: string;
	SUPABASE_URL: string;
	SOURCE_POINTER_MODE: string;
	SOURCE_STORAGE_BUCKET: string;
	WORKERS_SUBREQUEST_LIMIT: string;
	WORKERS_USAGE_PLAN: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BACKUP_ENVIRONMENT" | "SUPABASE_PROJECT_REF" | "SUPABASE_URL" | "SOURCE_POINTER_MODE" | "SOURCE_STORAGE_BUCKET" | "WORKERS_SUBREQUEST_LIMIT" | "WORKERS_USAGE_PLAN" | "SUPABASE_SERVICE_ROLE_KEY">> {}
}
