/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/deletion-scheduler/wrangler.staging.jsonc --include-runtime=false --strict-vars=false workers/deletion-scheduler/worker-configuration.d.ts` (hash: 84869a0e79c597156f36ef9fd34f727f)
interface __BaseEnv_Env {
	BURILLAB_RUNTIME_CONFIG: KVNamespace;
	DELETION_ENVIRONMENT: string;
	DELETION_TARGET_ORIGIN: string;
	RUNTIME_CONFIG_KEY: string;
	SCHEDULER_HEALTH_KEY: string;
	REQUEST_TIMEOUT_MS: string;
	DELETION_MAINTENANCE_SECRET: string;
	CF_ACCESS_CLIENT_ID: string;
	CF_ACCESS_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DELETION_ENVIRONMENT" | "DELETION_TARGET_ORIGIN" | "RUNTIME_CONFIG_KEY" | "SCHEDULER_HEALTH_KEY" | "REQUEST_TIMEOUT_MS" | "DELETION_MAINTENANCE_SECRET" | "CF_ACCESS_CLIENT_ID" | "CF_ACCESS_CLIENT_SECRET">> {}
}
