import type { PhStructureIdentity } from './catalogTypes';

export const PUBCHEM_IDENTITY_SOURCE_REF = 'PUBCHEM-PUG-REST-2026-08-04';

const pubchem = (pubchemCid: number, standardInchiKey: string): PhStructureIdentity => ({
    kind: 'pubchem',
    pubchemCid,
    standardInchiKey,
    sourceRef: PUBCHEM_IDENTITY_SOURCE_REF,
});

/**
 * Pinned exact-form identity snapshot. Formula is deliberately not used as an
 * automatic identity key because constitutional and stereochemical isomers
 * routinely share it.
 */
export const PH_STRUCTURE_IDENTITIES: Readonly<Record<string, PhStructureIdentity>> = Object.freeze({
    water: pubchem(962, 'XLYOFNOQVPJJNP-UHFFFAOYSA-N'),
    'hydrochloric-acid': pubchem(313, 'VEXZGXHMUGYJMC-UHFFFAOYSA-N'),
    'hydrobromic-acid': pubchem(260, 'CPELXLSAUQHCOX-UHFFFAOYSA-N'),
    'hydroiodic-acid': pubchem(24841, 'XMBWDFGMSWQBCA-UHFFFAOYSA-N'),
    'nitric-acid': pubchem(944, 'GRYLNZFGIOXLOG-UHFFFAOYSA-N'),
    'perchloric-acid': pubchem(24247, 'VLTRZXGMWDSKGL-UHFFFAOYSA-N'),
    'sodium-hydroxide': pubchem(14798, 'HEMHJVSKTPXQMS-UHFFFAOYSA-M'),
    'potassium-hydroxide': pubchem(14797, 'KWYUFKZDYYNOTN-UHFFFAOYSA-M'),
    'lithium-hydroxide': pubchem(3939, 'WMFOQBRAJBCJND-UHFFFAOYSA-M'),
    'sodium-chloride': pubchem(5234, 'FAPWRFPIFSIZLT-UHFFFAOYSA-M'),
    'potassium-chloride': pubchem(4873, 'WCUXLLCKKVVCTQ-UHFFFAOYSA-M'),
    'sodium-nitrate': pubchem(24268, 'VWDWKYIASSYTQR-UHFFFAOYSA-N'),
    'potassium-nitrate': pubchem(24434, 'FGIUAXJPYTZDNR-UHFFFAOYSA-N'),
    'sulfuric-acid': pubchem(1118, 'QAOWNCQODCNURD-UHFFFAOYSA-N'),
    'sodium-bisulfate': pubchem(516919, 'WBHQBSYUUJJSRZ-UHFFFAOYSA-M'),
    'sodium-sulfate': pubchem(24436, 'PMZURENOXWZQFD-UHFFFAOYSA-L'),
    'potassium-sulfate': pubchem(24507, 'OTYBMLCTZGSZBG-UHFFFAOYSA-L'),
    'phosphoric-acid': pubchem(1004, 'NBIIXXVUZAFLBC-UHFFFAOYSA-N'),
    'sodium-dihydrogen-phosphate': pubchem(23672064, 'AJPJDKMHJJGVTQ-UHFFFAOYSA-M'),
    'disodium-hydrogen-phosphate': pubchem(24203, 'BNIILDVGGAEEIG-UHFFFAOYSA-L'),
    'trisodium-phosphate': pubchem(24243, 'RYFMWSXOAZQYPI-UHFFFAOYSA-K'),
    'potassium-dihydrogen-phosphate': pubchem(516951, 'GNSKLFRGEWLPPA-UHFFFAOYSA-M'),
    'dipotassium-hydrogen-phosphate': pubchem(24450, 'ZPWVASYFFYYZEW-UHFFFAOYSA-L'),
    'hydrofluoric-acid': pubchem(14917, 'KRHYYFGTRYWZRS-UHFFFAOYSA-N'),
    'sodium-fluoride': pubchem(5235, 'PUZPDOWCWNUUKD-UHFFFAOYSA-M'),
    'potassium-fluoride': pubchem(522689, 'NROKBHXJSPEDAR-UHFFFAOYSA-M'),
    'boric-acid': pubchem(7628, 'KGBXLFKZBHKPEV-UHFFFAOYSA-N'),
    'carbonic-acid': {
        kind: 'pseudo_species',
        modelId: 'BURIL-AQ-POOL:H2CO3_STAR@25C',
        definition: 'CO2(aq) + H2CO3(aq)',
        selectable: false,
    },
    'sodium-bicarbonate': pubchem(516892, 'UIIMBOGNXHQVGW-UHFFFAOYSA-M'),
    'sodium-carbonate': pubchem(10340, 'CDBYLPFSWZWCQE-UHFFFAOYSA-L'),
    'potassium-carbonate': pubchem(11430, 'BWHMMNNQKKPAPP-UHFFFAOYSA-L'),
    ammonia: pubchem(222, 'QGZKDVFQNNGYKY-UHFFFAOYSA-N'),
    'ammonium-chloride': pubchem(25517, 'NLXLAEXVIDQMFP-UHFFFAOYSA-N'),
    'ammonium-sulfate': pubchem(6097028, 'BFNBIHQBYMNNAN-UHFFFAOYSA-N'),
    'acetic-acid': pubchem(176, 'QTBSBXVTEAMEQO-UHFFFAOYSA-N'),
    'sodium-acetate': pubchem(517045, 'VMHLLURERBWHNL-UHFFFAOYSA-M'),
    'potassium-acetate': pubchem(517044, 'SCVFZCLFOSHCOH-UHFFFAOYSA-M'),
    'formic-acid': pubchem(284, 'BDAGIHXWWSANSR-UHFFFAOYSA-N'),
    'sodium-formate': pubchem(2723810, 'HLBBKKJFGFRGMU-UHFFFAOYSA-M'),
    'propionic-acid': pubchem(1032, 'XBDQKXXYIPTUBI-UHFFFAOYSA-N'),
    'sodium-propionate': pubchem(2723816, 'JXKPEJDQGNYQSM-UHFFFAOYSA-M'),
    'butyric-acid': pubchem(264, 'FERIUCNNQQJTOY-UHFFFAOYSA-N'),
    'benzoic-acid': pubchem(243, 'WPYMKLBDIGXBTP-UHFFFAOYSA-N'),
    'sodium-benzoate': pubchem(517055, 'WXMKPNITSTVMEF-UHFFFAOYSA-M'),
    'lactic-acid': pubchem(612, 'JVTAAEKCZFNVCJ-UHFFFAOYSA-N'),
    'sodium-lactate': pubchem(23666456, 'NGSFWBMYFKHRBD-UHFFFAOYSA-M'),
    'oxalic-acid': pubchem(971, 'MUBZPKHOEPUJKR-UHFFFAOYSA-N'),
    'sodium-hydrogen-oxalate': pubchem(23684893, 'UJRAXLUXHBUNDO-UHFFFAOYSA-M'),
    'disodium-oxalate': pubchem(6125, 'ZNCPFRVNHGOPAG-UHFFFAOYSA-L'),
    'succinic-acid': pubchem(1110, 'KDYFGRWQOYBRFD-UHFFFAOYSA-N'),
    'disodium-succinate': pubchem(9020, 'ZDQYSKICYIVCPN-UHFFFAOYSA-L'),
    'malic-acid': pubchem(525, 'BJEPYKJPYRNKOW-UHFFFAOYSA-N'),
    'l-tartaric-acid': pubchem(444305, 'FEWJPZIEWOKRBE-JCYAYHJZSA-N'),
    'citric-acid': pubchem(311, 'KRKNYBCHXYNGOX-UHFFFAOYSA-N'),
    'trisodium-citrate': pubchem(6224, 'HRXKRNGNAMMEHJ-UHFFFAOYSA-K'),
    'tris-base': pubchem(6503, 'LENZDBCJOHFCAS-UHFFFAOYSA-N'),
    'tris-hydrochloride': pubchem(93573, 'QKNYBSVHEMOAJP-UHFFFAOYSA-N'),
    glycine: pubchem(750, 'DHMQDGOQFOQNFH-UHFFFAOYSA-N'),
    'glycine-hydrochloride': pubchem(22316, 'IVLXQGJVBGMLRR-UHFFFAOYSA-N'),
    'sodium-glycinate': pubchem(4684308, 'WUWHFEHKUQVYLF-UHFFFAOYSA-M'),
    'l-alanine': pubchem(5950, 'QNAYBMKLOCPYGJ-REOHCLBHSA-N'),
    'l-histidine': pubchem(6274, 'HNDVDQJCIGZPNO-YFKPBYRVSA-N'),
    mes: pubchem(78165, 'SXGZJKUKBWWHRA-UHFFFAOYSA-N'),
    mops: pubchem(70807, 'DVLFYONBTKHTER-UHFFFAOYSA-N'),
    pipes: pubchem(79723, 'IHPYMWDTONKSCO-UHFFFAOYSA-N'),
    hepes: pubchem(23831, 'JKMHFZQWWAIEOD-UHFFFAOYSA-N'),
    ches: pubchem(66898, 'MKWKNSIESPFAQN-UHFFFAOYSA-N'),
    caps: pubchem(70815, 'PJWWRFATQTVXHA-UHFFFAOYSA-N'),
});
