/**
 * Independent metrological references from NBS/NIST. These values are not
 * generated by PHREEQC and therefore exercise a separate validation path.
 * The published concentrations are molal; the predictor intentionally uses
 * the documented dilute-solution molarity-as-molality approximation.
 */
export const NIST_STANDARD_BUFFER_PROVENANCE = Object.freeze({
    sourceId: 'NIST-JRES-STANDARD-BUFFERS-1962',
    title: 'Revised Standard Values for pH Measurements from 0 to 95 C',
    url: 'https://nvlpubs.nist.gov/nistpubs/jres/066/2/V66.N02.A06.pdf',
    artifactSha256: 'd3f25e6eaa5a99286bd93410096189d93363c6443ba4a39a3f2f34e4cd2bbee4',
    temperatureC: 25,
    concentrationScale: 'molality',
});

export const NIST_STANDARD_BUFFER_CASES = Object.freeze([
    Object.freeze({
        id: 'nist-phosphate-equimolal-25c',
        referencePh: 6.865,
        components: Object.freeze([
            Object.freeze({ recordId: 'potassium-dihydrogen-phosphate', molal: 0.025 }),
            Object.freeze({ recordId: 'disodium-hydrogen-phosphate', molal: 0.025 }),
        ]),
    }),
    Object.freeze({
        id: 'nist-phosphate-physiological-25c',
        referencePh: 7.413,
        components: Object.freeze([
            Object.freeze({ recordId: 'potassium-dihydrogen-phosphate', molal: 0.008695 }),
            Object.freeze({ recordId: 'disodium-hydrogen-phosphate', molal: 0.03043 }),
        ]),
    }),
]);
